import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

export interface GeneratedFile {
  path: string;      // relative path e.g. "features/login.feature"
  content: string;
}

interface ManifestEntry {
  hash: string;  // SHA-256 of the content when MCP wrote it
}

/**
 * FileWriterService
 *
 * Handles writing the LLM-generated JSON file array to the project root on disk.
 * Single Responsibility: Only writes files, does not run tests or analyze code.
 *
 * 18B: Maintains a .mcp-manifest.json to track files written by the MCP.
 * If a file was manually modified since last write, surfaces a warning instead
 * of silently overwriting the human's work.
 */
export class FileWriterService {
  private readonly MANIFEST_FILE = '.mcp-manifest.json';

  private loadManifest(projectRoot: string): Record<string, ManifestEntry> {
    const manifestPath = path.join(projectRoot, this.MANIFEST_FILE);
    if (!fs.existsSync(manifestPath)) return {};
    try {
      return JSON.parse(fs.readFileSync(manifestPath, 'utf-8')) as Record<string, ManifestEntry>;
    } catch {
      return {};
    }
  }

  private saveManifest(projectRoot: string, manifest: Record<string, ManifestEntry>) {
    const manifestPath = path.join(projectRoot, this.MANIFEST_FILE);
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');
  }

  private sha256(content: string): string {
    return crypto.createHash('sha256').update(content).digest('hex');
  }

  /**
   * Writes every file in the array to disk under `projectRoot`.
   * Creates any intermediate directories automatically.
   * Warns if a file was manually modified since the last MCP write.
   * Returns the list of absolute paths written, plus any warnings.
   */
  public writeFiles(projectRoot: string, files: GeneratedFile[]): { written: string[]; warnings: string[] } {
    const written: string[] = [];
    const warnings: string[] = [];
    const manifest = this.loadManifest(projectRoot);

    for (const file of files) {
      const absolutePath = path.join(projectRoot, file.path);
      const dir = path.dirname(absolutePath);

      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      // 18B overwrite check: if file exists and wasn't generated by MCP (or was modified after)
      if (fs.existsSync(absolutePath)) {
        const existingContent = fs.readFileSync(absolutePath, 'utf-8');
        const existingHash = this.sha256(existingContent);
        const mcpEntry = manifest[file.path];
        if (mcpEntry != null && mcpEntry.hash !== existingHash) {
          warnings.push(`⚠️  "${file.path}" was manually modified since last MCP write. Overwriting with new generated version.`);
        }
      }

      fs.writeFileSync(absolutePath, file.content, 'utf-8');
      manifest[file.path] = { hash: this.sha256(file.content) };
      written.push(absolutePath);
    }

    this.saveManifest(projectRoot, manifest);
    return { written, warnings };
  }
}
