import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { validateProjectPath, auditGeneratedCode } from '../../utils/SecurityUtils.js';
import { FileGuard } from '../../utils/FileGuard.js';
import { ASTScrutinizer } from '../../utils/ASTScrutinizer.js';
import { StringMatcher } from '../../utils/StringMatcher.js';
import { FileSuggester } from '../../utils/FileSuggester.js';
import { McpErrors } from '../../types/ErrorSystem.js';
import type { StagingService } from '../execution/StagingService.js';
import type { FileStateService } from './FileStateService.js';
import { TsConfigManager } from '../../utils/TsConfigManager.js';

export interface GeneratedFile {
  path: string;      // relative path e.g. "features/login.feature"
  content: string;
}

interface ManifestEntry {
  hash: string;  // SHA-256 of the content when MCP wrote it
}

/**
 * FileWriterService
 *
 * Handles writing the LLM-generated JSON file array to the project root on disk.
 * Single Responsibility: Only writes files, does not run tests or analyze code.
 *
 * 18B: Maintains a .mcp-manifest.json to track files written by the MCP.
 * If a file was manually modified since last write, surfaces a warning instead
 * of silently overwriting the human's work.
 *
 * Phase 35: Enforces a directory allow-list and path traversal guard.
 * Only files targeting safe directories can be written by the LLM.
 */
export class FileWriterService {
  private readonly MANIFEST_FILE = '.mcp-manifest.json';

  /** Directories that LLM-generated files are allowed to be written into */
  private readonly ALLOWED_DIRS = ['features', 'step-definitions', 'pages', 'test-data', 'fixtures', 'models'];

  private loadManifest(projectRoot: string): Record<string, ManifestEntry> {
    const manifestPath = path.join(projectRoot, this.MANIFEST_FILE);
    if (!fs.existsSync(manifestPath)) return {};
    try {
      return JSON.parse(FileGuard.readTextFileSafely(manifestPath)) as Record<string, ManifestEntry>;
    } catch {
      return {};
    }
  }

  private saveManifest(projectRoot: string, manifest: Record<string, ManifestEntry>) {
    const manifestPath = path.join(projectRoot, this.MANIFEST_FILE);
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');
  }

  private sha256(content: string): string {
    return crypto.createHash('sha256').update(content).digest('hex');
  }

  /**
   * Writes every file in the array to disk under `projectRoot`.
   * Creates any intermediate directories automatically.
   * Warns if a file was manually modified since the last MCP write.
   *
   * Phase 35 Security:
   *  - Validates that every file path stays within projectRoot (no traversal)
   *  - Enforces a directory allow-list (only safe dirs for LLM-generated code)
   *
   * Returns the list of absolute paths written, plus any warnings.
   */
  public writeFiles(projectRoot: string, files: GeneratedFile[], dryRun: boolean = false): { written: string[]; warnings: string[] } {
    const written: string[] = [];
    const warnings: string[] = [];
    const manifest = this.loadManifest(projectRoot);

    for (const file of files) {
      // Phase 35: Path traversal guard
      let absolutePath: string;
      try {
        absolutePath = validateProjectPath(projectRoot, file.path);
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        warnings.push(`⛔ BLOCKED: "${file.path}" — ${msg}`);
        continue;
      }

      // Phase 35: Directory allow-list enforcement
      const topDir = file.path.split(/[/\\]/)[0] ?? '';
      if (!topDir || !this.ALLOWED_DIRS.includes(topDir)) {
        warnings.push(
          `⛔ BLOCKED: "${file.path}" — writes are only allowed in: ${this.ALLOWED_DIRS.join(', ')}. ` +
          `To modify root-level files, use the appropriate dedicated tool (manage_config, manage_env, etc.).`
        );
        continue;
      }

      // TASK-72: Auto-add path mapping to tsconfig.json
      if (!dryRun) {
        TsConfigManager.addPathMapping(projectRoot, topDir);
      }

      const dir = path.dirname(absolutePath);
      if (!fs.existsSync(dir)) {
        TsConfigManager.ensureParentDirs(absolutePath);
      }

      // 18B overwrite check: if file exists and wasn't generated by MCP (or was modified after)
      if (fs.existsSync(absolutePath)) {
        try {
          const existingContent = FileGuard.readTextFileSafely(absolutePath);
          const existingHash = this.sha256(existingContent);
          const mcpEntry = manifest[file.path];
          if (mcpEntry != null && mcpEntry.hash !== existingHash) {
            warnings.push(`⚠️  "${file.path}" was manually modified since last MCP write. Overwriting with new generated version.`);
          }
        } catch (e: any) {
          warnings.push(`⛔ BLOCKED: "${file.path}" cannot be read/overwritten due to error: ${e.message}`);
          continue;
        }
      }

      if (!dryRun) {
        fs.writeFileSync(absolutePath, file.content, 'utf-8');
        manifest[file.path] = { hash: this.sha256(file.content) };
      }
      written.push(absolutePath);
    }

    if (!dryRun) {
      this.saveManifest(projectRoot, manifest);
    }
    return { written, warnings };
  }

  /**
   * Validates generated files using ASTScrutinizer and tsc --noEmit (via StagingService),
   * then writes if valid. Returns a JSON string with structured feedback.
   */
  public async validateAndWrite(
    projectRoot: string,
    files: GeneratedFile[],
    stagingService: StagingService,
    fileStateService: FileStateService,
    dryRun: boolean = false
  ): Promise<string> {
    // Step 1: Stub Hunter — hard-reject files with incomplete implementations
    for (const file of files) {
      if (file.path.endsWith('.ts') || file.path.endsWith('.js')) {
        try {
          ASTScrutinizer.scrutinize(file.content, file.path);
        } catch (stubError: any) {
          return JSON.stringify({
            success: false,
            phase: 'stub-hunter',
            error: stubError.message || String(stubError),
            file: file.path,
            hint: 'The code is incomplete. You generated a stub, empty block, or TODO. You MUST provide the full, working implementation without placeholders before writing.'
          }, null, 2);
        }
      }
    }

    if (dryRun) {
      const writeResult = this.writeFiles(projectRoot, files, true);
      const secretViolations = auditGeneratedCode(files);
      return JSON.stringify({
        success: true,
        dryRun: true,
        written: writeResult.written,
        warnings: writeResult.warnings,
        secretViolations: secretViolations.length > 0 ? secretViolations : undefined,
        message: `Dry run complete. Validated ${files.length} files.`
      }, null, 2);
    }

    let stagingDir: string | undefined;
    try {
      // Step 2: File-State Race Guard
      fileStateService.validateWriteState(projectRoot, files);

      // Step 3: Atomic Staging with tsc
      stagingDir = await stagingService.stageAndValidate(projectRoot, files);
    } catch (error: any) {
      if (stagingDir) stagingService.cleanup(stagingDir);
      return JSON.stringify({
        success: false,
        phase: stagingDir ? 'tsc' : 'file-state',
        error: error.message || String(error),
        hint: stagingDir ? 'Fix the TypeScript compilation errors before saving.' : 'Resolve file state conflict and try again.'
      }, null, 2);
    }

    // Step 4: Write files to disk
    try {
      const writeResult = this.writeFiles(projectRoot, files, false);
      const secretViolations = auditGeneratedCode(files);
      
      return JSON.stringify({
        success: true,
        written: writeResult.written,
        warnings: writeResult.warnings,
        secretViolations: secretViolations.length > 0 ? secretViolations : undefined,
        message: `Successfully validated and wrote ${writeResult.written.length} files.`
      }, null, 2);
    } finally {
      if (stagingDir) stagingService.cleanup(stagingDir);
    }
  }

  /**
   * Replaces a specific string block within an existing file using fuzzy matching.
   * Leverages StringMatcher to handle LLM quote/whitespace inconsistencies.
   */
  public async replaceInFile(
    projectRoot: string,
    filePath: string,
    oldString: string,
    newString: string,
    stagingService: StagingService,
    fileStateService: FileStateService,
    dryRun: boolean = false
  ): Promise<string> {
    const fullPath = path.join(projectRoot, filePath);
    if (!fs.existsSync(fullPath)) {
      const enhanced = FileSuggester.enhanceError(fullPath);
      throw McpErrors.fileNotFound(enhanced, 'FileWriterService');
    }

    const content = FileGuard.readTextFileSafely(fullPath);
    fileStateService.recordRead(projectRoot, fullPath, content);
    
    const result = StringMatcher.fuzzyReplace(oldString, newString, content);
    if (!result.modified) {
      throw McpErrors.stringNotFound(oldString.substring(0, 50) + '...', 'FileWriterService');
    }

    return this.validateAndWrite(projectRoot, [{ path: filePath, content: result.content }], stagingService, fileStateService, dryRun);
  }
}
