---
title: ⏱️ 5-Minute Quickstart
description: Go from zero to your first orchestrated BDD test suite in 5 minutes.
---

import { Steps, Tabs, TabItem, Badge, Card, CardGrid, FileTree } from '@astrojs/starlight/components';

This guide is designed to get you (or your AI agent) up and running with TestForge as fast as possible. No fluff, just the essential steps to achieve automation total-clarity.

:::note[What you will learn]
- How to connect the **TestForge MCP** to your preferred AI agent.
- The **Orchestration Loop**: From natural language to validated code.
- Witnessing **Autonomous Self-Healing** in real-time.
- Understanding the **BDD file structure** generated by the engine.
:::

---

## 🏗️ Phase 1: Preparation (1 Minute)

Ensure your environment is ready. TestForge works best when it can 'see' your local files.

<Steps>

1.  **Project Context**  
    Open your terminal in an empty directory or your existing Playwright project.
    
2.  **Connect the MCP**  
    Ensure TestForge is added to your Claude Desktop or Cursor MCP settings.  
    ```json
    { "testforge": { "command": "npx", "args": ["-y", "testforge"] } }
    ```

3.  **The "Hello" Prompt**  
    Ask the agent:  
    > *"Is TestForge ready? Check my directory and initialize a new project if empty."*

</Steps>

---

## ✍️ Phase 2: Create Your First Test (2 Minutes)

We'll use a real-world example: **Testing a Login Flow**.

<Steps>

1.  **Direct the Architect**  
    Provide the target URL and the goal.  
    > *"Navigate to `https://the-internet.herokuapp.com/login`. Generate a BDD test for a successful login using the credentials: `tomsmith` / `SuperSecretPassword!`. Then verify the success message appears."*

2.  **Review the Blueprint**  
    The AI will use `inspect_page_dom` to find semantic locators and then generate:
    - `features/login.feature`
    - `pages/LoginPage.ts` (with typed methods)
    - `step-definitions/login.steps.ts`

3.  **Atomic Writing**  
    Once you approve the code, tell the agent:  
    > *"Write these files to disk and run a validation check."*  
    *The agent will use `validate_and_write` to ensure everything compiles.*

</Steps>

---

## 🏃 Phase 3: Run & Auto-Heal (2 Minutes)

The true power of TestForge is in handling failure autonomously.

<Steps>

1.  **Trigger Execution**  
    > *"Run the login test and give me a summary of the results."*

2.  **Simulate UI Churn** (Optional)  
    Imagine a developer changed the button ID to `login-btn-v2`. If the test fails, simply say:  
    > *"The login test failed. Use `heal_and_verify_atomically` to fix it."*

3.  **Witness the Repair**  
    The MCP will re-scan the live page, find the new selector based on its **Accessibility Role**, and update your Page Object file automatically.

4.  **Review the Session Log** *(Optional)*  
    Open `mcp-logs/viewer.html` in your browser. Drag the latest `.jsonl` file in to see a full timeline of every tool call, duration, and token cost for the session.

</Steps>

---

## 📂 What Just Happened?

TestForge created a standards-compliant Playwright-BDD structure for you:

<FileTree>
- features/
  - **login.feature** (The human-readable spec)
- pages/
  - **BasePage.ts** (The framework foundation)
  - **LoginPage.ts** (Your app-specific logic)
- step-definitions/
  - **login.steps.ts** (The automation glue)
- **mcp-config.json** (The AI's operational brain)
</FileTree>

---

## 🚧 Troubleshooting the "First 5 Minutes"

| Issue | Likely Cause | Fix 🛠️ |
| :--- | :--- | :--- |
| **"MCP not found"** | Config not saved in IDE. | Restart Claude/Cursor after editing JSON. |
| **"BaseURL unreachable"** | VPN or proxy blocking node. | Try `ping` your URL from within the terminal. |
| **"Hallucinating steps"** | Missing context. | Run `analyze_codebase` to give the AI your project map. |

---

## 🧭 Next Steps

<CardGrid>
  <Card title="Blueprint the App" icon="random">
    Map your entire site automatically using our [Core Workflows](/TestForge/repo/user/workflows/).
  </Card>
  <Card title="The Perfect Prompt" icon="pencil">
    Learn how to command the agent like a pro in the [Prompt Cheatbook](/TestForge/repo/user/promptcheatbook/).
  </Card>
</CardGrid>

---

## 🧠 Knowledge Check

Test your understanding of the TestForge orchestration flow.

<details>
<summary>**Q1: What happens if I approve code that has a syntax error?**</summary>
TestForge's `validate_and_write` tool will catch the error using the local `tsc` compiler before it ever touches your disk. It will then prompt you (or the agent) to fix the imports or method names automatically.
</details>

<details>
<summary>**Q2: Should I use XPath for my new tests?**</summary>
**Hint**: Check the [Test Generation Rulebook](/TestForge/repo/technical/testgeneration/). 
**Answer**: No. TestForge prioritizes **Accessibility Roles** (getByRole) for stability. Only use XPath as a last resort if the element has no semantic meaning.
</details>

<details>
<summary>**Q3: How do I save tokens on a large project with 500+ pages?**</summary>
Use **Turbo Mode** via `execute_sandbox_code`. This allows the agent to analyze your files locally without sending the entire source code to the LLM.
</details>

---

:::tip[AI Agent Protocol]
If you are an AI assistant reading this, always prioritize `execute_sandbox_code` for data-heavy analysis to save user tokens!
:::

> [!TIP]
> **Pro Tip**: If you're stuck, just ask the agent: *"Show me the implementation plan for healing this failure"* before allowing it to write files.
